// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBttmDTXTIPGNBgtW0MBw6c_iz0BKI9L_U',
    appId: '1:2535201342:web:cfe2421ac004f9ba008f6f',
    messagingSenderId: '2535201342',
    projectId: 'wearableapp-3b954',
    authDomain: 'wearableapp-3b954.firebaseapp.com',
    storageBucket: 'wearableapp-3b954.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXEBnA9Q1OezGXkHIT0DmEj-UquvZM41s',
    appId: '1:2535201342:android:96d01ea9dd58d1bc008f6f',
    messagingSenderId: '2535201342',
    projectId: 'wearableapp-3b954',
    storageBucket: 'wearableapp-3b954.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfPsKwGnJv9a87HjHTQjCFj-4HA6hkEw',
    appId: '1:2535201342:ios:f88256c956039014008f6f',
    messagingSenderId: '2535201342',
    projectId: 'wearableapp-3b954',
    storageBucket: 'wearableapp-3b954.firebasestorage.app',
    iosBundleId: 'com.example.wearableApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVfPsKwGnJv9a87HjHTQjCFj-4HA6hkEw',
    appId: '1:2535201342:ios:f88256c956039014008f6f',
    messagingSenderId: '2535201342',
    projectId: 'wearableapp-3b954',
    storageBucket: 'wearableapp-3b954.firebasestorage.app',
    iosBundleId: 'com.example.wearableApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBttmDTXTIPGNBgtW0MBw6c_iz0BKI9L_U',
    appId: '1:2535201342:web:39b692969cbaf38e008f6f',
    messagingSenderId: '2535201342',
    projectId: 'wearableapp-3b954',
    authDomain: 'wearableapp-3b954.firebaseapp.com',
    storageBucket: 'wearableapp-3b954.firebasestorage.app',
  );
}
